# Configure the base image
ARG PYTHON_VERSION=3.10
# Use CUDA development image instead of runtime to include nvcc and build tools
FROM nvidia/cuda:12.9.1-cudnn-devel-ubuntu22.04@sha256:1cb02388491c05441f8963d42bc38b6ec5462fba95a8e3bb2cb8e6091f0738c8
# Configure environment variables
ENV DEBIAN_FRONTEND=noninteractive \
    MUJOCO_GL=egl \
    PATH=/lerobot/.venv/bin:$PATH \
    CUDA_HOME=/usr/local/cuda \
    NVCC_APPEND_FLAGS=-allow-unsupported-compiler

# Install system dependencies and uv (as root)
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential git curl libglib2.0-0 libegl1-mesa-dev ffmpeg \
    libusb-1.0-0-dev speech-dispatcher libgeos-dev portaudio19-dev \
    cmake python3-dev pkg-config libavformat-dev libavcodec-dev \
    libavdevice-dev libavutil-dev libswscale-dev libswresample-dev libavfilter-dev \
    && curl -LsSf https://astral.sh/uv/install.sh | sh \
    && mv /root/.local/bin/uv /usr/local/bin/uv \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

# Create application directory and set permissions
WORKDIR /lerobot

# Create the virtual environment
# We use a virtual environment inside the container—even though the container itself \
# provides isolation—to closely resemble local development and allow users to \
# run other Python projects in the same container without dependency conflicts.
RUN uv venv --python 3.10
ENV VIRTUAL_ENV=/lerobot/.venv

# Install Python dependencies for caching
COPY pyproject.toml README.md MANIFEST.in ./
COPY src/ src/
RUN uv pip install --no-cache ".[all]" azureml-mlflow


# Copy the rest of the application code
# Make sure to have the git-LFS files for testing
COPY . .

# Set the default command
CMD ["/bin/bash"]
